// Builds a plain-text summary of a full strategy result, suitable for
// handing off to a designer, printing, or emailing — the individual
// per-card Copy buttons only grab one piece of text at a time, this
// grabs the whole campaign in one file.
export function buildStrategyText(result) {
  const lines = [];
  const rule = "─".repeat(60);

  lines.push(`MARKETING STRATEGY — ${result.product || "Untitled product"}`);
  lines.push(`Generated: ${new Date().toLocaleString()}`);
  lines.push(rule);
  lines.push("");

  if (result.final_recommendation) {
    lines.push("★ AI'S FINAL RECOMMENDATION (combines all analyses below)");
    lines.push(result.final_recommendation.recommendation || "");
    lines.push("");
    lines.push(`Why: ${result.final_recommendation.rationale || ""}`);
    lines.push(`Best used for: ${result.final_recommendation.best_for || ""}`);
    lines.push("");
    lines.push(rule);
    lines.push("");
    lines.push("SUPPORTING ANALYSIS FROM EACH AI AGENT:");
    lines.push("");
  }

  if (result.component1_full || result.component1) {
    const c1 = result.component1_full
      ? {
          strategy: result.component1_full.recommendation.strategy,
          copy: result.component1_full.recommendation.strategy === "emotional"
            ? result.component1_full.generated_copy.emotional.text
            : result.component1_full.generated_copy.rational.text,
        }
      : { strategy: result.component1.strategy, copy: result.component1.recommended_copy };

    lines.push("BUYING PSYCHOLOGY — Recommended Copy");
    lines.push(`(${c1.strategy} approach)`);
    lines.push(c1.copy);
    lines.push("");
  }

  if (result.component3) {
    lines.push(rule);
    lines.push(`URGENCY & SCARCITY — ${result.component3.recommended_intensity?.toUpperCase()} intensity`);
    lines.push(result.component3.final_copy || "");
    lines.push("");
  }

  if (result.component24) {
    lines.push(rule);
    lines.push(`EMOTIONAL APPEAL (target feeling: ${result.component24.target_emotion})`);
    lines.push(result.component24.emotion_copy || "");
    lines.push("");
    lines.push("LOSS-FRAMED VERSION (use sparingly, for genuine limited-time offers)");
    lines.push(result.component24.loss_message || "");
    lines.push("");

    if (result.component24.visual_suggestions) {
      lines.push(rule);
      lines.push("VISUAL DIRECTION");
      lines.push(`Color palette: ${result.component24.visual_suggestions.palette}`);
      lines.push(`Image style: ${result.component24.visual_suggestions.image_style}`);
      lines.push(`Layout mood: ${result.component24.visual_suggestions.layout_mood}`);
      lines.push("");
    }
  }

  lines.push(rule);
  lines.push("Note: this copy was generated by AI. Please review all claims for accuracy");
  lines.push("before publishing — verify any statistics, comparisons, or specific claims");
  lines.push("against your actual product before using this in ads or listings.");

  return lines.join("\n");
}

export function downloadStrategy(result) {
  const text = buildStrategyText(result);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const safeName = (result.product || "strategy").replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  a.href = url;
  a.download = `${safeName}-marketing-strategy.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
